# Aliases
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias ssh='autossh -M 0'

# set editor to vim
export EDITOR='vim'

# set PATH
export PATH=/usr/local/bin:$PATH

# ls color
export CLICOLOR=1

# History
#HISTSIZE=1000000
